### ISSUE TITLE
Please help to run

### ISSUE THREAD

**Issue by tuananhcwrs** [TrillCyborg/fullstack#11]
Hello @TrillCyborg ,

I seemed to miss something that I can run it.
Or the description might be out of date.

Could you please help on checking?
Thank you.

**Comment by TrillCyborg** [comment]
did you run mongo? what error are you getting?

**Comment by TrillCyborg** [comment]
does it work when you run `yarn gen:types:watch` in ./client ?

**Comment by tuananhcwrs** [comment]
Hello there,

Thanks for your reply.

Do I need to run:
"Yarn start" in ./client?  --> because it cannot resolve development.env.json.

And just info for you that when I run "yarn watch" in ./server, it says "server starts at local:400" while with "yarn gen:types:watch" in client, it opens local:3000.

Thanks.

P/S: what with Android and iOS folders, they are for react web apps? not mobile apps?

**Comment by TrillCyborg** [comment]
try running this from client folder `cp ./src/config/example.env.json ./src/config/development.env.json`

this project uses react native web. i have not tested on ios and android but you should be able to run the client as react native apps on those platforms
