### ISSUE TITLE
Error retrieving info for public key. [plaid]

### ISSUE THREAD

**Issue by Googlewasmyidea** [TrillCyborg/fullstack#17]
```
POST https://sandbox.plaid.com/link/client/get 400 (Bad Request)

Make sure that the entered key is correct. Find your public key in your Dashboard (https://dashboard.plaid.com/account/keys).
```

As far as I can see the keys are correct. Is the new "ACCOUNTS_SECRET": "", field in the env file the "secret" field for "sandbox" on this page: https://dashboard.plaid.com/account/keys  or have I missed something?

Thanks in advance!

**Comment by TrillCyborg** [comment]
did you add the correct key to the client config file?

**Comment by Googlewasmyidea** [comment]
Hello,

Thanks so much for your reply, the issue is solved.

People having similar issues, please make sure you enter the correct details. Leave the "ACCOUNTS_SECRET" as is (which was "secret" by default) and make sure that the secret key you enter on install is from the "Sandbox" section NOT development. (At least this is what solved my issues.) 

Trill, Thank you for open sourcing this, appreciate it man :)
