### ISSUE TITLE
我觉得：老板付钱的话，你也别要钱了

### ISSUE THREAD

**Issue by candyadmin** [TrillCyborg/fullstack#19]
在没付钱的时候， 你这样开源可以说是发泄和维权的手段，但是一旦他付钱，你就会因此而成了泄密的罪名。  等待你的可能是法律的诉讼。  

因此 ，你开源时肯定想好了，坚决和这个公司断绝联系吧

**Comment by fan624009652** [comment]
付钱是不可能付钱的，开源前都没付钱，开源后付钱也没用了啊，网上现在到处都是。
