### ISSUE TITLE
Google Maps JavaScript API error: InvalidKeyMapError

### ISSUE THREAD

**Issue by danyow** [TrillCyborg/fullstack#21]
Login succeeded, but address verification failed.

**Comment by danyow** [comment]
Solved the problem,
But a new problem。。。。。


This API project is not authorized to use this API. Please ensure this API is activated in the Google Developers Console: https://console.developers.google.com/apis/api/places_backend?project=_ For more information on authentication and Google Maps JavaScript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by TrillCyborg** [comment]
did you create an API key?

**Comment by danyow** [comment]
yes

**Comment by danyow** [comment]
Places API
Places API
Places API
Enable
