### ISSUE TITLE
 Error: connect ECONNREFUSED 127.0.0.1:4000

### ISSUE THREAD

**Issue by kosvrouvas** [TrillCyborg/fullstack#23]
Any clue why I get this? 

 ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/generated/graphql.tsx
      ✖ Load GraphQL schemas
        → connect ECONNREFUSED 127.0.0.1:4000
        Load GraphQL documents
        Generate

 Found 1 error

  ✖ src/generated/graphql.tsx
    Error: connect ECONNREFUSED 127.0.0.1:4000

  ℹ Watching for changes...

**Comment by jackwilsdon** [comment]
Are you sure you're actually running `mongod`?

**Comment by elie222** [comment]
You need to run the server on port 4000 first.

**Comment by franva** [comment]
I npm installed the mongod:
`npm install mongod`

under the fullstack folder and typed
`mongod`
in the command line console.

It shows me this error:

> 
> 'mongod' is not recognized as an internal or external command,
> operable program or batch file.

**Comment by elie222** [comment]
You need to install mongo on your computer. It’s not an npm package. Google
“install mongo” for instructions.

**Comment by kosvrouvas** [comment]
dang it. I guess you are right. mongodb is missing

Any good tutorial for macOS?

**Comment by elie222** [comment]
Google install mongodb. It’s very easy. Potentially one line in the command
line.
