### ISSUE TITLE
When i input my address,nothing happened. 

### ISSUE THREAD

**Issue by liangshangyu** [TrillCyborg/fullstack#30]
is that because of my google-map key is wrong?

**Comment by TrillCyborg** [comment]
This is my assumption. You'll need to get a new one from the link I left at the bottom of the readme and put it in the client config file

**Comment by HannanSolo** [comment]
Hey Jason, Im having the same problem as above, and I already tried to make a new key and made sure the Places API was enabled.

Any other ideas?
