### ISSUE TITLE
UserContext

### ISSUE THREAD

**Issue by vko-online** [TrillCyborg/fullstack#31]
Why UserContext is located in screens folder?

**Comment by TrillCyborg** [comment]
Good question. I like to things that are only relevant to a specific screen in that screens folder. The router does use it as well but following the Rule of Three it should be used by one more place before getting refactored out into some other more orginized area https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)

**Comment by elie222** [comment]
If you have suggestions for a better place to put it happy to hear.

The utils folder may be the best place for it. The logic for putting it in
routes was viewing the routes folder as grouping by features so everything
in routes/user was related to auth stuff.
